#!/usr/bin/env bash
# transfers a file from our client to a serve
PATH_TO_SSH_KEY=$4
PATH_TO_FILE=$1
USERNAME=$3
IP=$2
if [ $# -lt 4 ];
then
	 echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
elif [ $# -eq 4 ];
then
	scp -o "StrictHostKeyChecking=no" -i "$PATH_TO_SSH_KEY" "$PATH_TO_FILE" "$USERNAME"@"$IP":~/
fi
