#!/usr/bin/env bash
# Install nginx on your web-01 server
sudo apt-get update
sudo apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sed -i '/listen 80 default_server;/a rewrite ^/redirect_me/ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanet;' /etc/nginx/sites-avaliable/default
service nginx start
