#!/usr/bin/env bash
# configure web-02 to be identical to web-01

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sudo sed -i '/listen 80 default_server;/a add_server X-Served-By $hostname;' /etc/nginx/nginx.conf
service nginx start
