#!/usr/bin/env bash
# Install HAproxy on your lb-01 server.

sudo apt-get update
sudo apt-get -y install haproxy
echo "
frontend fe_main
        mode http
        bind *:80
        default_backend be_main

backend be_main
        mode http
        balance roundrobin
        server 682-web-01 35.237.161.199
        server 682-web-02 35.231.115.177 " >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
