#!/usr/bin/env bash
# Install HAproxy on your lb-01 server.

sudo apt-get update
sudo apt-get install haproxy
printf "\n\nfrontend fe_main\n\tmode http\n\tbind *:80\n\tdefault_backend be_main\n\nbackend be_main\n\tmode http\n\tbalance roundrobin\n\tserver 682-web-01 35.237.161.199\n\tserver 682-web-02 35.231.115.177" >> /etc/haproxy/haproxy.cfg
