#!/usr/bin/env bash
#  that displays Holberton School 10 times, but for the 9th iteration, displays
#  Holberton School and then Hi on a new line.
a=1
while [ $a -le 10 ]
do
    echo "Holberton School"
    if [ $a -eq 9 ]
    then
	echo "Hi"
    fi
    (( a++ ))
done
