#!/usr/bin/env bash
# Run Nginx as Nginx
sudo pkill apache2
chmod 755 /etc/nginx/sites-enabled/default
sed -i 's/listen 80/8080/' /etc/nginx/sites-enabled/default
sed -i 's/#user www-data; /user nginx;/'
sudo -u nginx service nginx restart
